---
title: "Client Report - Introduction"
subtitle: "Course DS 250"
author: "Tristan Stubblefield"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

### Introduction

This is the report and findings from project 0 as part of the DS 250 course. Identifying that the setup is working correctly and that I can submit assingments as demonstrated here.

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


## Elevator pitch
This week in DS 250 we were tasked in finishing the course setup for the class. I was able to get everything working and now I am in the process of learning how to apply the knowledge I gained and troubleshooting the software and packages. I learned how to use quarto markdown github. I understand this is not a proper elevator pitch with numerical data and it is sumamrizing, but this is Project 0 and I want to make sure everything is executed correctly.

```{python}
#| label: project-data
#| code-summary: Read and format project data

# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pd.read_csv("https://raw.githubusercontent.com/byuidatascience/data4python4ds/master/data-raw/mpg/mpg.csv")
```

__Highlight the Questions and Tasks__

## Question|Task 1

__Finish the Course Setup, and post any questions to getting your environment working smoothly in your course Slack channel__

I completed the course setup. Including downloading vs code, python 3.11.7 and all packages. I also installed Quarto, and made a Github account and cloned the repository. 

```{python}
#| label: Q1
#| code-summary: Read and format data
# Include and execute your code here


```

## Question|Task 2

__Recreate the example chart from PY4DS: CH2 Data Visualization of the textbook.__

- _There is a positive correlation in flipper length and body mass for all three species of penguins studied: Adelie, Gentoo, and Chinstrap. Adelies data is the most sparsed and has a higher amount of outliers that have shorter flipper lengths but a higher body mass. Chinstrap and Adelie both have a tigher concentration that is more evenly distributed across the data set.

```{python}
#| label: Q1-chart
#| code-summary: plot example
#| fig-cap: "Correlation of flipper length to body mass of penguin species"
#| fig-align: center
# Include and execute your code here
import pandas as pd
from palmerpenguins import load_penguins
from lets_plot import *

penguins = load_penguins()

LetsPlot.setup_html()

(
    ggplot(
        data=penguins,
        mapping=aes(x="flipper_length_mm", y="body_mass_g", color="species"),
    )
    + geom_point()
    + geom_smooth(method="lm")
)
  
```

## Question|Task 3

__Include the table created from PY4DS: CH2 Data Visualization used to create the above chart__

- _This is the data set that the graph was pulled from. 

```{python}
#| label: Q1-table
#| code-summary: table example
#| tbl-cap: "table example"
#| tbl-cap-location: top
# Include and execute your code here

penguins = load_penguins()
penguins

display(penguins)
```
